build_mau:
  outputs:
    dev:
      account: CTB52544
      database: dev
      password: Varshurao23
      role: ACCOUNTADMIN
      schema: raw_data
      threads: 1
      type: snowflake
      user: varshurao23
      warehouse: compute_wh
  target: dev
